version: '3.2'
services:
  rabbitmq:
    container_name: 'rabbit-mq'
    image: rabbitmq:3.11.3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./rabbitmq-config/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq-config/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
