
server:
  port: 8087
spring:
  rabbitmq:
    host: localhost
  application:
    name: shipping-service
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5433/shippingdb
    username: shippingdbuser
    password: rainbow
management:
  endpoints:
    web:
      exposure:
        include: health, info