version: '3.1'
services:
  db:
    container_name: 'order-db'
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=orderdb
      - POSTGRES_USER=orderdbuser
      - POSTGRES_PASSWORD=secret
  application:
    container_name: 'order-service'
    image: order-service:1
    ports:
      - '8085:8085'
    profiles: ['order-service']
    environment:
      POSTGRES_JDBC_USER: orderdbuser
      POSTGRES_JDBC_PASS: secret
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/orderdb"
      SPRING_PROFILES_ACTIVE: local
