
server:
  port: 8086
spring:
  rabbitmq:
    host: localhost
  application:
    name: payment-service
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5434/paymentdb
    username: paymentdbuser
    password: unicorn
management:
  endpoints:
    web:
      exposure:
        include: health, info