
server:
  port: 8085
spring:
  rabbitmq:
    host: localhost
  application:
    name: order-service
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: orderdbuser
    password: secret
management:
  endpoints:
    web:
      exposure:
        include: health, info