version: '3.1'
services:
  db:
    container_name: 'order-db'
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=orderdb
      - POSTGRES_USER=orderdbuser
      - POSTGRES_PASSWORD=secret
  order-service:
    container_name: 'order-service'
    image: order-service:1
    ports:
      - '8085:8085'
    profiles: ['order-service']
    environment:
      POSTGRES_JDBC_USER: orderdbuser
      POSTGRES_JDBC_PASS: secret
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/orderdb"
      SPRING_PROFILES_ACTIVE: local
  db2:
    container_name: 'payment-db'
    image: postgres:alpine
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_DB=paymentdb
      - POSTGRES_USER=paymentdbuser
      - POSTGRES_PASSWORD=unicorn
  payment-service:
    container_name: 'payment-service'
    image: payment-service:1
    ports:
      - '8086:8086'
    profiles: ['payment-service']
    environment:
      POSTGRES_JDBC_USER: paymentdbuser
      POSTGRES_JDBC_PASS: unicorn
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/paymentdb"
      SPRING_PROFILES_ACTIVE: local
  db3:
    container_name: 'shipping-db'
    image: postgres:alpine
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=shippingdb
      - POSTGRES_USER=shippingdbuser
      - POSTGRES_PASSWORD=rainbow
  shipping-service:
    container_name: 'shipping-service'
    image: shipping-service:1
    ports:
      - '8086:8086'
    profiles: [ 'shipping-service' ]
    environment:
      POSTGRES_JDBC_USER: shippingdbuser
      POSTGRES_JDBC_PASS: rainbow
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/shippingdb"
      SPRING_PROFILES_ACTIVE: local
  gateway-service:
      container_name: 'gateway-service'
      image: gateway-service:1
      ports:
        - '8080:8080'
      profiles: ['gateway-service']
      environment:
        catservice_baseurl: 'http://catservice:8080/api'
        SPRING_PROFILES_ACTIVE: local
